name: Auto Update Changelog

on:
    push:
        branches:
            - master

jobs:
    update-changelog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Get the current version
              id: current-version
              run: echo "::set-output name=version::$(python setup.py --version)"

            - name: Update Changelog
              run: |
                  version=${{steps.current-version.outputs.version}}
                  changelog="# Changelog\n\n## v${version}\n\n### Changed\n\n"
                  for commit in $(git log --pretty='- %s' HEAD^..HEAD); do
                    changelog="${changelog}- ${commit}\n"
                  done
                  echo "${changelog}" > CHANGELOG.md

            - name: Commit Changelog
              run: |
                  git add CHANGELOG.md
                  git commit -m "Updated changelog"

            - name: Push Changelog
              run: |
                  git push
