name: Update Changelog

on:
    push:
        branches:
            - master

jobs:
    update-changelog:
        runs-on: ubuntu-latest

        env:
            version:

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get the current version
              id: current-version
              run: echo "version=$(python setup.py --version)" >> $GITHUB_ENV
              
            - name: auto-update-changelog
              uses: MusfiqDehan/Auto-Update-CHANGELOG@v0.11.0
              with:
                  name: Md. Musfiqur Rahaman
                  email: musfiqur.rahaman@northsouth.edu
