name: Update Changelog

on:
    push:
        branches:
            - master

jobs:
    update-changelog:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Get the current version
              id: current-version
              run: echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV

            - name: Check if the commit message matches the release pattern
              run: |
                  if [[ $(git log -1 --pretty=%B) != "Update changelog for v${{ steps.current-version.outputs.version }}" ]]; then
                    echo "Commit message does not match the release pattern."
                    exit 1
                  fi

            - name: Update changelog
              if: contains(github.event.head_commit.message, 'Update changelog for v${{ env.VERSION }}')
              run: |
                  export PREVIOUS_VERSION=$(git tag -l --sort=-creatordate | head -n 1)
                  export CHANGES=$(git log --pretty="- %s" $PREVIOUS_VERSION..)
                  printf "# v${{ env.VERSION }}\n\n## Changes\n$CHANGES\n" > $GITHUB_WORKSPACE/CHANGELOG.md
