name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - name: Install dependencies
              run: pip3 install -r requirements.txt
            - name: Get the current version
              id: current-version
              run: echo "::set-output name=version::$(python setup.py --version)"
            - name: Check if the commit message matches the release pattern
              run: |
                  if [[ $(git log -1 --pretty=%B) != "Release v${{ steps.current-version.outputs.version }}" ]]; then
                    echo "Commit message does not match the release pattern."
                    exit 1
                  fi
            - name: Create a release
              run: |
                  python3 setup.py sdist bdist_wheel
                  git config user.email "musfiqur.rahaman@northsouth.edu"
                  git config user.name "Md. Musfiqur Rahaman"
                  git tag -a "v${{ steps.current-version.outputs.version }}" -m "Release v${{ steps.current-version.outputs.version }}"
                  git push --follow-tags

            - name: Set Environment Variables
              run: |
                  LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
                  CURRENT_TAG=$(echo ${{ github.ref }} | sed 's/^refs\/tags\///')

                  echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
                  echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV

            - name: Get Commit Log
              run: |
                  COMMITS=$(git log ${{ env.LATEST_TAG }}..${{ env.CURRENT_TAG }} --pretty=format:'- %s' --reverse)

                  echo "::set-output name=commits::$COMMITS"

            - name: Create a GitHub release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.current-version.outputs.version }}
                  release_name: Release v${{ steps.current-version.outputs.version }}
                  body: ${{ steps.get-commit-log.outputs.commits }}

            - name: Upload release to PyPI
              uses: pypa/gh-action-pypi-publish@v1.8.6
              with:
                  user: ${{ secrets.PYPI_USERNAME }}
                  password: ${{ secrets.PYPI_PASSWORD }}
