name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Get the current version
              id: current-version
              run: echo "::set-output name=version::$(python setup.py --version)"
            - name: Check if the commit message matches the release pattern
              run: |
                  if [[ $(git log -1 --pretty=%B) != "Release v${{ steps.current-version.outputs.version }}" ]]; then
                    echo "Commit message does not match the release pattern."
                    exit 1
                  fi
            - name: Create a release
              run: |
                  python setup.py sdist bdist_wheel
                  git tag -a "v${{ steps.current-version.outputs.version }}" -m "Release v${{ steps.current-version.outputs.version }}"
                  git push --follow-tags
            - name: Upload release to PyPI
              uses: pypa/gh-action-pypi-publish@v1.8.6
              with:
                  user: ${{ secrets.PYPI_USERNAME }}
                  password: ${{ secrets.PYPI_PASSWORD }}
